version: '3.9'
services:
  web:
    image: "django-boilerplate:dev"
    build:
      target: development_build
      context: ..
      args:
        DJANGO_ENV: development
    command: "python -Wd manage.py wait_for_db &&
              python -Wd manage.py migrate &&
              python -Wd manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
      - "3000:3000"
    env_file:
      - ./.env
    volumes:
      - ${PROJECT_PATH}:/code
      - static-volume:/code/static
      - media-volume:/code/media
    depends_on:
      - db

  db:
    image: postgres:13.2-alpine
    restart: unless-stopped
    ports:
      - "$DOCKER_DB_EXTERNAL_PORT:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  poetry:
    build: ..
    image: app
    volumes:
      - ${PROJECT_PATH}:/code

volumes:
  postgres_data:
  static-volume:
  media-volume:
